[package]
name = "lambda_http_wrapper"
version = "0.1.0"
edition = "2021"

[lib]
name = "lambda_http_wrapper"
path = "src/lambda_http_wrapper.rs"

[dependencies]
lambda_http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
