[package]
name = "function_one"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "function_one"
path = "src/function_one.rs"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }

# internal dependencies
lambda_http_wrapper = { path = "../../libraries/lambda_http_wrapper"}
